name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint:nofix
      - name: Build
        run: yarn build
      - name: Build storybook
        run: yarn build-storybook
        if: github.ref != 'refs/heads/master'
      - name: Deploy storybook
        env:
          GH_TOKEN: ${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}
        run: yarn deploy-storybook
        if: github.ref == 'refs/heads/master'
